sudo: required #this gives travis root permissions
services:
    - docker

before_install: # things we want done initially
    - docker build -t test-image -f Dockerfile.dev .

script:
    - docker run test-image npm run test -- --coverage
      
