version: '3'
services: 
    react-app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        tty: true
        stdin_open: true
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules # this is saying don't try to map it to anything locally
            - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
